# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/francisco/Documents/tryStr/t2STRUCK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/francisco/Documents/tryStr/t2STRUCK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francisco/Documents/tryStr/t2STRUCK/CMakeFiles /home/francisco/Documents/tryStr/t2STRUCK/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francisco/Documents/tryStr/t2STRUCK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named STRUCK

# Build rule for target.
STRUCK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STRUCK
.PHONY : STRUCK

# fast build rule for target.
STRUCK/fast:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/build
.PHONY : STRUCK/fast

Config.o: Config.cpp.o
.PHONY : Config.o

# target to build an object file
Config.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Config.cpp.o
.PHONY : Config.cpp.o

Config.i: Config.cpp.i
.PHONY : Config.i

# target to preprocess a source file
Config.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Config.cpp.i
.PHONY : Config.cpp.i

Config.s: Config.cpp.s
.PHONY : Config.s

# target to generate assembly for a file
Config.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Config.cpp.s
.PHONY : Config.cpp.s

Features.o: Features.cpp.o
.PHONY : Features.o

# target to build an object file
Features.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Features.cpp.o
.PHONY : Features.cpp.o

Features.i: Features.cpp.i
.PHONY : Features.i

# target to preprocess a source file
Features.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Features.cpp.i
.PHONY : Features.cpp.i

Features.s: Features.cpp.s
.PHONY : Features.s

# target to generate assembly for a file
Features.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Features.cpp.s
.PHONY : Features.cpp.s

GraphUtils.o: GraphUtils.cpp.o
.PHONY : GraphUtils.o

# target to build an object file
GraphUtils.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/GraphUtils.cpp.o
.PHONY : GraphUtils.cpp.o

GraphUtils.i: GraphUtils.cpp.i
.PHONY : GraphUtils.i

# target to preprocess a source file
GraphUtils.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/GraphUtils.cpp.i
.PHONY : GraphUtils.cpp.i

GraphUtils.s: GraphUtils.cpp.s
.PHONY : GraphUtils.s

# target to generate assembly for a file
GraphUtils.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/GraphUtils.cpp.s
.PHONY : GraphUtils.cpp.s

HaarFeature.o: HaarFeature.cpp.o
.PHONY : HaarFeature.o

# target to build an object file
HaarFeature.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HaarFeature.cpp.o
.PHONY : HaarFeature.cpp.o

HaarFeature.i: HaarFeature.cpp.i
.PHONY : HaarFeature.i

# target to preprocess a source file
HaarFeature.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HaarFeature.cpp.i
.PHONY : HaarFeature.cpp.i

HaarFeature.s: HaarFeature.cpp.s
.PHONY : HaarFeature.s

# target to generate assembly for a file
HaarFeature.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HaarFeature.cpp.s
.PHONY : HaarFeature.cpp.s

HaarFeatures.o: HaarFeatures.cpp.o
.PHONY : HaarFeatures.o

# target to build an object file
HaarFeatures.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HaarFeatures.cpp.o
.PHONY : HaarFeatures.cpp.o

HaarFeatures.i: HaarFeatures.cpp.i
.PHONY : HaarFeatures.i

# target to preprocess a source file
HaarFeatures.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HaarFeatures.cpp.i
.PHONY : HaarFeatures.cpp.i

HaarFeatures.s: HaarFeatures.cpp.s
.PHONY : HaarFeatures.s

# target to generate assembly for a file
HaarFeatures.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HaarFeatures.cpp.s
.PHONY : HaarFeatures.cpp.s

HistogramFeatures.o: HistogramFeatures.cpp.o
.PHONY : HistogramFeatures.o

# target to build an object file
HistogramFeatures.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HistogramFeatures.cpp.o
.PHONY : HistogramFeatures.cpp.o

HistogramFeatures.i: HistogramFeatures.cpp.i
.PHONY : HistogramFeatures.i

# target to preprocess a source file
HistogramFeatures.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HistogramFeatures.cpp.i
.PHONY : HistogramFeatures.cpp.i

HistogramFeatures.s: HistogramFeatures.cpp.s
.PHONY : HistogramFeatures.s

# target to generate assembly for a file
HistogramFeatures.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/HistogramFeatures.cpp.s
.PHONY : HistogramFeatures.cpp.s

ImageRep.o: ImageRep.cpp.o
.PHONY : ImageRep.o

# target to build an object file
ImageRep.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/ImageRep.cpp.o
.PHONY : ImageRep.cpp.o

ImageRep.i: ImageRep.cpp.i
.PHONY : ImageRep.i

# target to preprocess a source file
ImageRep.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/ImageRep.cpp.i
.PHONY : ImageRep.cpp.i

ImageRep.s: ImageRep.cpp.s
.PHONY : ImageRep.s

# target to generate assembly for a file
ImageRep.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/ImageRep.cpp.s
.PHONY : ImageRep.cpp.s

LaRank.o: LaRank.cpp.o
.PHONY : LaRank.o

# target to build an object file
LaRank.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/LaRank.cpp.o
.PHONY : LaRank.cpp.o

LaRank.i: LaRank.cpp.i
.PHONY : LaRank.i

# target to preprocess a source file
LaRank.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/LaRank.cpp.i
.PHONY : LaRank.cpp.i

LaRank.s: LaRank.cpp.s
.PHONY : LaRank.s

# target to generate assembly for a file
LaRank.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/LaRank.cpp.s
.PHONY : LaRank.cpp.s

MultiFeatures.o: MultiFeatures.cpp.o
.PHONY : MultiFeatures.o

# target to build an object file
MultiFeatures.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/MultiFeatures.cpp.o
.PHONY : MultiFeatures.cpp.o

MultiFeatures.i: MultiFeatures.cpp.i
.PHONY : MultiFeatures.i

# target to preprocess a source file
MultiFeatures.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/MultiFeatures.cpp.i
.PHONY : MultiFeatures.cpp.i

MultiFeatures.s: MultiFeatures.cpp.s
.PHONY : MultiFeatures.s

# target to generate assembly for a file
MultiFeatures.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/MultiFeatures.cpp.s
.PHONY : MultiFeatures.cpp.s

RawFeatures.o: RawFeatures.cpp.o
.PHONY : RawFeatures.o

# target to build an object file
RawFeatures.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/RawFeatures.cpp.o
.PHONY : RawFeatures.cpp.o

RawFeatures.i: RawFeatures.cpp.i
.PHONY : RawFeatures.i

# target to preprocess a source file
RawFeatures.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/RawFeatures.cpp.i
.PHONY : RawFeatures.cpp.i

RawFeatures.s: RawFeatures.cpp.s
.PHONY : RawFeatures.s

# target to generate assembly for a file
RawFeatures.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/RawFeatures.cpp.s
.PHONY : RawFeatures.cpp.s

Sampler.o: Sampler.cpp.o
.PHONY : Sampler.o

# target to build an object file
Sampler.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Sampler.cpp.o
.PHONY : Sampler.cpp.o

Sampler.i: Sampler.cpp.i
.PHONY : Sampler.i

# target to preprocess a source file
Sampler.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Sampler.cpp.i
.PHONY : Sampler.cpp.i

Sampler.s: Sampler.cpp.s
.PHONY : Sampler.s

# target to generate assembly for a file
Sampler.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Sampler.cpp.s
.PHONY : Sampler.cpp.s

Tracker.o: Tracker.cpp.o
.PHONY : Tracker.o

# target to build an object file
Tracker.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Tracker.cpp.o
.PHONY : Tracker.cpp.o

Tracker.i: Tracker.cpp.i
.PHONY : Tracker.i

# target to preprocess a source file
Tracker.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Tracker.cpp.i
.PHONY : Tracker.cpp.i

Tracker.s: Tracker.cpp.s
.PHONY : Tracker.s

# target to generate assembly for a file
Tracker.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/Tracker.cpp.s
.PHONY : Tracker.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/STRUCK.dir/build.make CMakeFiles/STRUCK.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... STRUCK"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Config.o"
	@echo "... Config.i"
	@echo "... Config.s"
	@echo "... Features.o"
	@echo "... Features.i"
	@echo "... Features.s"
	@echo "... GraphUtils.o"
	@echo "... GraphUtils.i"
	@echo "... GraphUtils.s"
	@echo "... HaarFeature.o"
	@echo "... HaarFeature.i"
	@echo "... HaarFeature.s"
	@echo "... HaarFeatures.o"
	@echo "... HaarFeatures.i"
	@echo "... HaarFeatures.s"
	@echo "... HistogramFeatures.o"
	@echo "... HistogramFeatures.i"
	@echo "... HistogramFeatures.s"
	@echo "... ImageRep.o"
	@echo "... ImageRep.i"
	@echo "... ImageRep.s"
	@echo "... LaRank.o"
	@echo "... LaRank.i"
	@echo "... LaRank.s"
	@echo "... MultiFeatures.o"
	@echo "... MultiFeatures.i"
	@echo "... MultiFeatures.s"
	@echo "... RawFeatures.o"
	@echo "... RawFeatures.i"
	@echo "... RawFeatures.s"
	@echo "... Sampler.o"
	@echo "... Sampler.i"
	@echo "... Sampler.s"
	@echo "... Tracker.o"
	@echo "... Tracker.i"
	@echo "... Tracker.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

